# Generated by Django 6.0.1 on 2026-01-21 02:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='headline',
        ),
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(default='Apparently, this user prefers to keep an air of mystery about them.', verbose_name='About'),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.TextField(default='Location is not specified.', verbose_name='Place of residence'),
        ),
        migrations.AddField(
            model_name='profile',
            name='summary',
            field=models.TextField(default='New user on our platform!', verbose_name='Summary about user'),
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Skill name')),
                ('description', models.TextField(verbose_name='Skill description')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
        ),
    ]
