# Generated by Django 6.0.1 on 2026-01-21 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_profile_bio_remove_profile_headline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='social_X',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_website',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='social_youtube',
        ),
    ]
