# Generated by Django 6.0.1 on 2026-01-19 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_vote_ratio'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured_image',
            field=models.ImageField(blank=True, default='default-proj.png', null=True, upload_to=''),
        ),
    ]
