# Generated by Django 6.0.1 on 2026-01-20 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_project_demo_link_alter_project_source_link'),
        ('users', '0002_remove_profile_email_remove_profile_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='developer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.profile'),
        ),
    ]
